### PR TITLE
Move channel to use libbeat implementation

### PR DESCRIPTION
**Pull request by ruflin**
See https://github.com/elastic/libbeat/pull/51

Please merge https://github.com/elastic/libbeat/pull/51 first

### CODE REVIEW

**Comment by urso** [comment]
Just minor detail, but do we want to pass the *Beat around everywhere? Why not store it on init in actual instance?

**Comment by ruflin** [comment]
You mean storing it in the beater object?

**Comment by urso** [comment]
Yep. Can be optional.

**Comment by ruflin** [comment]
@urso I made it Topbeat specific for the moment.

**Comment by urso** [comment]
+1

**Comment by ruflin** [comment]
@urso Done. I must put it as git hook on my machine.

**Comment by ruflin** [comment]
Pull request closed in favor of future event changes from @urso

**Pull request closed without merging**
