### PR TITLE
improve periodic ticker handling

### PR DESCRIPTION
**Pull request by urso**
- stop ticker when done
- no need to drop ticks, as dropping is already done by ticker
- detect possible tick drop by comparing processing duration to period

### CODE REVIEW

**Comment by ruflin** [comment]
LGTM. Changelog?

**Comment by urso** [comment]
Changelog is in another already merge PR. This one is a cleanup after reading NewTicker doc again

**Comment by ruflin** [comment]
@urso Merged. Can you link the other PR to this one for reference?

**Comment by urso** [comment]
continuation of #77

**Pull request merged**
